image: node:latest

stages:
  - Test
  - Deploy
cache:
  paths:
    - node_modules/


testing_testing:
  stage: Test
  tags:
    - docker
  before_script:
    - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
    - npm install
    - npm install supertest
  script:
    - npm test

production:
  type: deploy
  tags:
    - shell
  stage: Deploy
  script:
  - ls
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - git add .
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/redr-disaster-simulator.git || true
  - git push
  only:
    - master