image: node:latest

stages:
  - Deploy
cache:
  paths:
    - node_modules/




production:
  type: deploy
  stage: Deploy
  image: ruby:latest
  script:
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --redr-disaster-simulator=node-heroku-dpl --api-key$HEROKU_API_KEY
  only:
    - master
