image: node:latest

stages:
  - test
cache:
  paths:
    - node_modules/




testing_testing:
  stage: test
  tags:
  - docker
  before_script:
    - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
    - npm install
    - npm install supertest
  script:
  - npm test
