image: node:latest

stages:
  - test
cache:
  paths:
    - node_modules/



run_server:
  stage: test
  tags:
    - docker

  before_script:
    - npm install
  script:
    - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
    - node server.js

testing_testing:
  stage: test
  tags:
  - docker
  before_script:
    - npm install
  script:
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - npm test
