image: node:latest

stages:
  - lint
  - Test
  - Deploy
  - DeployTesting
cache:
  paths:
    - node_modules/
    
    
eslint:
  stage: lint
  tags:
    - docker
  before_script:
    - cd disaster-master/disaster-master-product
    - npm install
    
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    - eslint server.js
    - eslint autoevents.js
    - eslint resources/js/run-simulation.js
    - eslint resources/js/ngo-simulation.js
    - eslint resources/js/scenario-edit.js


testing_testing:
  stage: Test
  tags:
    - docker
  before_script:
    - cd disaster-master/disaster-master-product
    - npm install
    - npm install supertest
  script:
    - npm test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

  
    
deploytesting:
  type: deploy
  tags:
    - deploy
  stage: Deploy
  image: ruby:latest
  script:
  - sudo apt-get update -qy
  - sudo apt-get install -y ruby-dev
  - sudo gem install dpl
  - cd cd disaster-master/disaster-master-product
  - sudo dpl --provider=heroku --app=disaster-simulator-testing --api-key=$HEROKU_API_KEY
  only:
  - heroku-bug-fixes
  - lachlan-features-part3
  - overlayMultimediaIntegration
  - quick-mocha-pipeline-test
  - Tags-Implementation
  - scenario-creation
  - ngo-passkey-display
  - lachlan-review
  - graceful-simulation-termination



production:
  type: deploy
  tags:
    - deploy
  stage: Deploy
  image: ruby:latest
  script:
  - sudo apt-get update -qy
  - sudo apt-get install -y ruby-dev
  - sudo gem install dpl
  - cd cd disaster-master/disaster-master-product
  - sudo dpl --provider=heroku --app=redr-disaster-simulator --api-key=$HEROKU_API_KEY
  only:
  - master
