image: node:latest

stages:
  - build
  - test
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
  - docker
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  tags:
  - docker
  script:
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - node server.js
  - npm test
