image: node:latest

stages:
  - Test
  - Deploy
cache:
  paths:
    - node_modules/


testing_testing:
  stage: Test
  tags:
    - docker
  before_script:
    - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
    - npm install
    - npm install supertest
  script:
    - npm test

production:
  type: deploy
  tags:
    - shell
  stage: Deploy
  image: ruby:latest
  script:
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - apk update
  - apk add
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --redr-disaster-simulator=node-heroku-dpl --api-key$HEROKU_API_KEY
  only:
    - master