image: node:latest

stages:
  - build
  - test

services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: simulationData
  MYSQL_ROOT_PASSWORD: root

#Host: mysql
#User: root
#Password: root
#Database: simulationData

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
  - docker
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

connect:
  image: mysql
  stage: build
  tags:
  - docker
  script:
  - service mysql start
  - echo mysql -u root
  - echo "SELECT 'OK';" | mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -h mysql "$MYSQL_DATABASE"
  - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -h localhost < "data/db/scripts/create-db.sql"
  - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -h localhost < "data/db/scripts/init-db-tables.sql"

testing_testing:
  stage: test
  tags:
  - docker
  script:
  - cd DisasterSimulatorNodeJSServer/mysql-8.0.16-winx64/bin
  - start mysqld
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - node server.js
