image: node:latest
issue_closing_pattern: '\b((?:[Cc]los(?:e[sd]?|ing)|\b[Ff]ix(?:e[sd]|ing)?|\b[Rr]esolv(?:e[sd]?|ing)|\b[Ii]mplement(?:s|ed|ing)?)(:?) +(?:(?:issues? +)?%{issue_ref}(?:(?:, *| +and +)?)|([A-Z][A-Z0-9_]+-\d+))+)'


stages:
  - Test
  - Deploy
  - DeployTesting
cache:
  paths:
    - node_modules/


testing_testing:
  stage: Test
  tags:
    - docker
  before_script:
    - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
    - npm install
    - npm install supertest
  script:
    - npm test
    
deploytesting:
  type: deploy
  tags:
    - deploy
  stage: Deploy
  image: ruby:latest
  script:
  - sudo apt-get update -qy
  - sudo apt-get install -y ruby-dev
  - sudo gem install dpl
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - sudo dpl --provider=heroku --app=disaster-simulator-testing --api-key=$HEROKU_API_KEY
  only:
  - heroku-bug-fixes


production:
  type: deploy
  tags:
    - deploy
  stage: Deploy
  image: ruby:latest
  script:
  - sudo apt-get update -qy
  - sudo apt-get install -y ruby-dev
  - sudo gem install dpl
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - sudo dpl --provider=heroku --app=redr-disaster-simulator --api-key=$HEROKU_API_KEY
  only:
  - master