image: node:latest



stages:
  - Test
  - Deploy
  - DeployTesting
cache:
  paths:
    - node_modules/


testing_testing:
  stage: Test
  tags:
    - docker
  before_script:
    - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
    - npm install
    - npm install supertest
  script:
    - npm test
    
deploytesting:
  type: deploy
  tags:
    - deploy
  stage: Deploy
  image: ruby:latest
  script:
  - sudo apt-get update -qy
  - sudo apt-get install -y ruby-dev
  - sudo gem install dpl
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - sudo dpl --provider=heroku --app=disaster-simulator-testing --api-key=$HEROKU_API_KEY
  only:
  - heroku-bug-fixes
  - lachlan-features-part3


production:
  type: deploy
  tags:
    - deploy
  stage: Deploy
  image: ruby:latest
  script:
  - sudo apt-get update -qy
  - sudo apt-get install -y ruby-dev
  - sudo gem install dpl
  - cd RedR-Disaster-Simulator/DisasterSimulatorNodeJSServer
  - sudo dpl --provider=heroku --app=redr-disaster-simulator --api-key=$HEROKU_API_KEY
  only:
  - master